apiVersion: v2
name: operaton
description: |
  Helm chart for Operaton
type: application
version: 1.0.23
appVersion: 2.2.0-M1
keywords: 
  - bpm
  - bpmn
  - operaton
  - operaton-engine
  - dmn
  - process-engine
  - workflow
icon: https://operaton.github.io/operaton-helm/operaton-logo.png
home: https://operaton.org
sources:
  - https://github.com/operaton/operaton-helm/tree/main/charts/operaton
  - https://github.com/operaton/operaton-docker
  - https://github.com/operaton/operaton
maintainers:
  - name: Jaye
    url: https://github.com/jmaster1985
dependencies:
  # https://github.com/bitnami/charts/tree/main/bitnami/postgresql
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 18.6.2
    condition: postgres.enabled
    alias: postgres
annotations:
  artifacthub.io/links: |
    - name: Operaton BPM Helm chart
      url: https://github.com/operaton/operaton-helm/tree/main/charts/operaton
    - name: Operaton BPM Docker
      url: https://github.com/operaton/operaton-docker
    - name: Operaton BPM
      url: https://github.com/operaton/operaton
  # This will be generated automatically by the release workflow.
  # https://github.com/operaton/operaton-helm/blob/main/.github/workflows/release.yaml
  artifacthub.io/changes: |
